### ISSUE TITLE
Resize a16z logo

### ISSUE THREAD

**Issue by mfburnett** [joininteract/joininteract.com#41]
Hey @schlosser would you mind helping me get a16z's logo to the same size as the other logos? Thank you!!

Screenshot (lol)

<img width="954" alt="screen shot 2019-03-04 at 9 49 36 pm" src="https://user-images.githubusercontent.com/6687345/53783799-fddc5480-3ec7-11e9-9a63-bfaf22357183.png">

File:

![a16z](https://user-images.githubusercontent.com/6687345/53783668-74c51d80-3ec7-11e9-9f10-0767a6614ec2.png)

**Comment by schlosser** [comment]
This will likely just require creating a new image that has more whitespace in it. I'll take a stab when I'm at my other computer.

**Comment by schlosser** [comment]
(or add one-off padding in CSS)
