### ISSUE TITLE
Change post h3 formatting

### ISSUE THREAD

**Issue by jhil** [joininteract/joininteract.com#46]
- Change `.post h3` from `max-width: 25rem;` to 'padding-right: 1rem;'
- Add `orphans: 2;` to prevent single word second lines (https://developer.mozilla.org/en-US/docs/Web/CSS/orphans)

**Comment by schlosser** [comment]
![blown](https://user-images.githubusercontent.com/2433509/60636986-9a672280-9de6-11e9-8d2f-9840a4dbecbf.gif)
