### ISSUE TITLE
Enable view only interactions on sheet

### ISSUE THREAD

**Issue by jhil** [joininteract/joininteract.com#59]
Can this enable field selection (for easy copying) and column manipulation (for per-session  sorting)? Is that something gsheet embeds can do?

<img width="1051" alt="Screen Shot 2019-07-03 at 12 04 07 AM" src="https://user-images.githubusercontent.com/2228347/60570316-2a916300-9d26-11e9-87ff-8727b8a83982.png">

**Comment by jhil** [comment]
Also, can top frozen row actually freeze/ be sticky?

**Comment by schlosser** [comment]
I don't think you can do any of that. We can disable scrolling, replace with image, prompt user to click to open in new tab, if you want

**Comment by schlosser** [comment]
[Confirmed](https://stackoverflow.com/questions/33318364/embedding-google-sheet-cells-that-can-be-sorted-by-viewers). I can easily get the data in, but I'd have to either (a) build this in html or (b) link to the external sheet

**Comment by jhil** [comment]
Wow, I thought embedding spreadsheet was way easier. How about search? That might be a good way to make it useful. Fine for now, v2 we should look at making this better.

**Comment by schlosser** [comment]
I think for search, people can expand to full screen and use ctrl+f. WDYT?

**Comment by jhil** [comment]
fine for an MVP
