### ISSUE TITLE
Use /members instead of members.

### ISSUE THREAD

**Issue by jhil** [joininteract/joininteract.com#63]
Or @mfburnett @dara do you have other ideas for the domain? Generally, subdomains complicate things and hurt seo.

**Comment by schlosser** [comment]
Are there other concerns other than SEO? We're not trying to get people to find our hidden members-only page :)

This makes things a bit more complicated as these are two different apps, for performance reasons.

**Comment by schlosser** [comment]
(I don't want to load a chunky react app to display our public website)

**Comment by jhil** [comment]
Sure that's fine.
