### ISSUE TITLE
Hook up fontawesome

### ISSUE THREAD

**Issue by jhil** [joininteract/joininteract.com#69]
Just checking if you plan on using the fontawesome library to enable an admin to code a resource or something with a specific fontawesome icon id to make it appear in the card. not sure how the spreadsheets are set up rn.

**Comment by schlosser** [comment]
I have this working, but not in use:

```js
import * as FontAwesome from 'react-icons/fa';

class MemberHome extends Component {
  render() {
    const icontest = "FaCoffee";
    const FaIcon = FontAwesome[icontest]
    return (
      <FaIcon/>
    )
}
```

**Comment by jhil** [comment]
Cool
