### ISSUE TITLE
Team data + integration

### ISSUE THREAD

**Issue by jhil** [joininteract/joininteract.com#72]

**Comment by mhseiden** [comment]
I've set up the following sheet as the backing database. [LINK](https://docs.google.com/spreadsheets/d/1UUC61AkvzgtnvT7wx8lOHHY49A3BOXQ-qPk7Rwp-lWY/edit#gid=1469374588)

**Comment by mhseiden** [comment]
The team data is now included as an embedded spreadsheet.
