### ISSUE TITLE
Add "fill out census CTA" in Members section.

### ISSUE THREAD

**Issue by mhseiden** [joininteract/joininteract.com#75]
Although we have email addresses for all members, we only list members who have filled out the census. As such, we should have a CTA that instructs folks who don't see their entry to fill out the census. Another approach is to swap "Update Info" to "Complete Census". Lots of options here 🙂

**Comment by jhil** [comment]
Sounds good! Please feel free to replace the link and update the content.

**Comment by schlosser** [comment]
Are these two different links @mhseiden? Or is it the same and we should just change the text?

**Comment by mhseiden** [comment]
Hm, this was a design question with some suggestions. In terms of user stories...

1. Users who haven't filled out the census should be prompted to do so.
2. Users who have filled out the census should be prompted to keep their submission up-to-date.

**Comment by schlosser** [comment]
I guess I'm asking if there is a different update form vs new submission form? Or do we just have one form?

**Comment by mhseiden** [comment]
I figure we can use one form to start, and just add a hyperlink to the "edit my submission" screen.

**Comment by schlosser** [comment]
I added logic to jump to the edit submission screen, pre-filled with the info in memberDatabase. If we referenced the census from the app we could get more, but not sure if we want to do that.
